# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Heartland Community Accupuncture
description: >- # this means to ignore newlines until "baseurl:"
  Heartland Community Acupuncture provides affordable acupuncture in a safe 
  and nurturing atmosphere. Licensed Acupuncturist Mara Bateman uses gentle 
  acupuncture techniques to relax the body and promote healing.
paymessage: Pay what you can; everyone is welcome.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.heartlandacu.com" # the base hostname & protocol for your site, e.g. http://example.com
contact: 
  email: wellness@heartlandacu.com
  phone: 541.760.5515
  address:
    street: "121 W Broadway Ave, Suite 12 (above the Orpheum Theater)"
    city: "Fairfield"
    state: "IA"
    zip: "52556"
  schedule: "https://www.schedulicity.com/scheduling/HCA5AW"
  hours:
    - day: Wednesday
      time: 1pm - 6pm
    - day: Thursday
      time: 9am - 2pm

menu:
  - title: Home
    url: /

  - title: About
    url: /about

  - title: Appointments
    url: /appointments

  - title: FAQs
    url: /faq

  - title: Contact
    url: /contact

collections:
  faq:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: "faq"
    values:
      layout: "faq/single"

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
