title: Heartland Community Accupuncture
description: >-
  Heartland Community Acupuncture provides affordable acupuncture in a safe  and
  nurturing atmosphere. Licensed Acupuncturist Mara Bateman uses gentle 
  acupuncture techniques to relax the body and promote healing.
paymessage: Pay what you can; everyone is welcome. YO YO YO
