backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "masthead", widget: "image", required: false}
      - {label: "Intro (optional)", name: "intro", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "faq" # Used in routes, e.g., /admin/collections/blog
    label: "Frequently Asked Questions" # Used in the UI
    folder: "_faq" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "faq/single"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "List Order", name: "order", widget: "number", required: false, default: 0, valueType: "int"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Settings"
    name: "settings"
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/settings/navigation.yml"
        fields:
          - label: Menu
            name: menu
            widget: list
            fields:
              - {label: Name, name: title, widget: string}
              - label: Page
                name: url
                widget: relation
                collection: pages
                searchFields: ['title']
                valueField: permalink
      - label: "Site"
        name: "site"
        file: "_data/settings/site.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: text}
          - {label: Payment Message, name: paymessage, widget: string}
          - {label: Email, name: email, widget: string, pattern: ['[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}', 'Enter a valid email address.']}
          - {label: Phone, name: phone, widget: string}
          - {label: Street, name: street, widget: string}
          - {label: City, name: city, widget: string}
          - {label: State, name: state, widget: string}
          - {label: Google Place ID, name: place_id, widget: string}
          - {label: Scheduling Link, name: schedule, widget: string, pattern: ['@^(https?|ftp)://[^\s/$.?#].[^\s]*$@iS', 'Enter a valid URL.']}
          - label: Hours
            name: hours
            widget: list
            fields:
              - label: Day
                name: day
                widget: select
                options: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
              - {label: Time, name: time, widget: string}
