title: Heartland Community Accupuncture
description: >-
  Heartland Community Acupuncture provides affordable acupuncture in a safe  and
  nurturing atmosphere. Licensed Acupuncturist Mara Bateman uses gentle 
  acupuncture techniques to relax the body and promote healing.
paymessage: Pay what you can; everyone is welcome.
footer_image: /assets/images/uploads/farm-with-mist.jpg
email: wellness@heartlandacu.com
phone: 541.760.5515
street: '121 W Broadway Ave, Suite 12 (above the Orpheum Theater)'
city: Fairfield
state: IA
place_id: ChIJv_-aDGxm5ocRjL02GOEvIHg
schedule: 'https://www.schedulicity.com/scheduling/HCA5AW'
hours:
  - day: Monday
    note: Closed
    time: ''
  - day: Tuesday
    note: Closed
    time: ''
  - day: Wednesday
    time: ''
    times:
      - close: 6pm
        open: 1pm
  - day: Thursday
    time: ''
    times:
      - close: 2pm
        open: 9am
  - day: Friday
    time: ''
    times:
      - close: 6pm
        open: 1pm
  - day: Saturday
    time: ''
    times:
      - close: 2pm
        open: 9am
  - day: Sunday
    time: ''
    times:
      - close: 5pm
        open: 1pm
