title: Heartland Community Accupuncture
description: >-
  Heartland Community Acupuncture provides affordable acupuncture in a safe  and
  nurturing atmosphere. Licensed Acupuncturist Mara Bateman uses gentle 
  acupuncture techniques to relax the body and promote healing.
paymessage: Pay what you can; everyone is welcome.
footer_image: /assets/images/uploads/farm-with-mist.jpg
email: wellness@heartlandacu.com
phone: 541.760.5515
street: '121 W Broadway Ave, Suite 12 (above the Orpheum Theater)'
city: Fairfield
state: IA
place_id: ChIJv_-aDGxm5ocRjL02GOEvIHg
schedule: 'https://www.schedulicity.com/scheduling/HCA5AW'
hours:
  - day: Monday
    note: Closed
  - day: Tuesday
    note: Closed
  - day: Wednesday
    times:
      - close: '18'
        open: '13'
  - day: Thursday
    times:
      - close: '14'
        open: 09
  - day: Friday
    times:
      - close: '18'
        open: '13'
  - day: Saturday
    times:
      - close: '14'
        open: 09
  - day: Sunday
    times:
      - close: '17'
        open: '13'
