title: Heartland Community Acupuncture
description: >-
  Heartland Community Acupuncture provides affordable acupuncture and massage in
  a safe  and nurturing atmosphere. Licensed Acupuncturist Mara Bateman uses
  gentle  acupuncture techniques to release tension and promote healing.
paymessage: Pay what you can; everyone is welcome.
footer_image: /assets/images/uploads/farm-with-mist.jpg
email: wellness@heartlandacu.com
phone: 541.760.5115
street: '121 W Broadway Ave, Suite 12'
city: Fairfield
state: IA
business_image: /assets/images/uploads/heartland-community-acupuncture.jpg
location_note: (above the Orpheum Theater)
place_id: ChIJv_-aDGxm5ocRjL02GOEvIHg
schedule: 'https://www.schedulicity.com/scheduling/HCA5AW'
hours:
  - day: Friday
    note: Community Acupuncture
    times:
      - close: '18'
        open: '14'
  - day: Saturday
    note: Community Acupuncture
    times:
      - close: '14'
        open: '10'
  - day: Wednesday
    note: Community Acupuncture Happy Hour!
    times:
      - close: '17'
        open: '16'
  - note: Click "Schedule Now" for Shiatsu & Shiatsu+Acu availability!
